# Generated by Django 3.2 on 2022-07-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='product',
            field=models.CharField(default='', max_length=200),
        ),
    ]
