# Generated by Django 3.2 on 2022-07-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_maintable_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintable',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='maintable',
            name='subcategories',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.RemoveField(
            model_name='maintable',
            name='subproducts',
        ),
        migrations.AddField(
            model_name='maintable',
            name='subproducts',
            field=models.CharField(default='', max_length=500),
        ),
    ]
